config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  resources :my_blogs
  resources :blogs
  root 'my_blogs#index'
  get 'home/about'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :my_blogs
end

app/models/my_blog.rb
class MyBlog < ApplicationRecord
    has_one_attached :image
    belongs_to :category
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :my_blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/my_blogs_controller.rb
class MyBlogsController < ApplicationController
  before_action :set_my_blog, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /my_blogs or /my_blogs.json
  def index
  @categories = Category.all

  cate = params[:cate]

  if !cate.nil?
    @my_blogs = MyBlog.where(:category_id => cate)
  else
    @my_blogs = MyBlog.all
  end
end
  # GET /my_blogs/1 or /my_blogs/1.json
  def show
  end

  # GET /my_blogs/new
  def new
    @my_blog = MyBlog.new
  end

  # GET /my_blogs/1/edit
  def edit
  end

  # POST /my_blogs or /my_blogs.json
  def create
    @my_blog = MyBlog.new(my_blog_params)

    respond_to do |format|
      if @my_blog.save
        format.html { redirect_to my_blog_url(@my_blog), notice: "My blog was successfully created." }
        format.json { render :show, status: :created, location: @my_blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @my_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_blogs/1 or /my_blogs/1.json
  def update
    respond_to do |format|
      if @my_blog.update(my_blog_params)
        format.html { redirect_to my_blog_url(@my_blog), notice: "My blog was successfully updated." }
        format.json { render :show, status: :ok, location: @my_blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @my_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_blogs/1 or /my_blogs/1.json
  def destroy
    @my_blog.destroy

    respond_to do |format|
      format.html { redirect_to my_blogs_url, notice: "My blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_blog
      @my_blog = MyBlog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def my_blog_params
      params.require(:my_blog).permit(:title, :body, :category_id, :image, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/my_blogs_helper.rb
module MyBlogsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @category.category %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg background-color nav-background">
    <a class="navbar-brand" href="#">My Blogs</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <%# <span class="navbar-toggler-icon"></span> %>
<i class="fa-solid fa-bars"></i>
        </button>
        
    <div class="container">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to 'Home',root_path,class:"nav-link "%>
                </li>
                <%# <li class="nav-item">
                    <%= link_to 'About',home_about_path,class:"nav-link "%>
                <%# </li>  %>
                <% if user_signed_in? %>
                    <li class="nav-item">
                        <%= link_to 'Create Blog',new_my_blog_path,class:"nav-link " %>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'Sign Out',destroy_user_session_path, method: :delete,class:"nav-link"%>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'Edit User',edit_user_registration_path,class:"nav-link"%>
                    </li> 
                <% else %>
                     <li class="nav-item">
                        <%= link_to 'Sign Up',new_user_registration_path,class:"nav-link"%>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'Sign In',new_user_session_path,class:"nav-link"%>
                    </li>
                <% end %>
               
             
            </ul>
        </div> 
    </div>
    
</nav>

app/views/home/about.html.erb
<p>this is about us page</p>

app/views/home/index.html.erb
<%# <h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p> %>

app/views/layouts/_alerts.html.erb
<br/>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# <%= stylesheet_link_tag 'style.css'%>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%=render 'home/header'%>
  <% if notice %>
    <%=render 'layouts/alerts' %>    
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/my_blogs/_form.html.erb
<%= form_with(model: my_blog) do |form| %>
  <% if my_blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(my_blog.errors.count, "error") %> prohibited this my_blog from being saved:</h2>

      <ul>
        <% my_blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
   <div class="flex-row d-flex justify-content-center">
    <div class="col-md-8">
  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class:'form-control'%>
  </div>

  <div class="field form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class:'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :category %>
    <%= form.select :category_id, Category.all.map {|c| [c.category,c.id]}, class:'sachin' %>
  </div>
  
  <div class="field form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class:'form-control' %>
  </div>

   <div class="field form-group">
    <%= form.label :body %>
    <%= form.number_field :user_id,id: :my_blog_user_id,value:current_user.id,class:'form-control' ,type: :hidden%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

  </div>
<% end %>

app/views/my_blogs/edit.html.erb
<h1>Editing My Blog</h1>

<%= render 'form', my_blog: @my_blog %>

<%= link_to 'Show', @my_blog %> |
<%= link_to 'Back', my_blogs_path %>

app/views/my_blogs/index.html.erb
  
<div class="mix">
  <div class=" container container-data">  
    <% @my_blogs.each do |my_blog| %>
      <div class=" blog-start">
        <div class="my_card card">
          <div class="img-card my-img">
            <% if my_blog.image.present? %>
              <%= image_tag my_blog.image,class:"blog-img" %>
            <% end %>
          </div>
          <div class="card-body">
            <h1 class="card-title display-6"><%= my_blog.title %></h1>
            <p class="card-text"><%= my_blog.body %></p>
            <p class="lead">
            <%= link_to 'Read More..', my_blog, class: "btn btn-primary"%>
            </p>

            <% if user_signed_in? %>
               <%= link_to 'Edit', edit_my_blog_path(my_blog) %> |
            <%= link_to 'Destroy', my_blog, method: :delete, data: { confirm: 'Are you sure?' }, class: "link" %>
            <% end %>
           
          </div>
        </div> 
      </div>
    
        
    <% end %>


  </div>
  <div class="side-bar">
    <div class="col-md-3">
      <div class="card category"   >
        <div class="card-header">
          <h4>Categories</span></h4>
        </div>
        <div class="card-body">
          <ul class="list-group">
            <% @categories.each do |category|%>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <%= link_to category.category, my_blogs_path(:cate => category.id)%>         
                <span class="blog-span"><%= category.my_blogs.count%></span>
              </li>
            <%end%>
          </ul>
        </div>
    </div>
    <div class="col-md-3">
      <div class="card category"   >
        <div class="card-header">
          <h4>Recent Post</span></h4>
        </div>
        <div class="card-body">
          <ul class="list-group">
            <% @my_blogs.last(3).each do |blog|%>
              <li class="li st-group-item d-flex justify-content-between align-items-center">
              <%= link_to blog.title,blog %> 
              <hr/>
<%# <%= link_to blog.title image_tag(blog.image) ,blog %> 
              </li>
            <%end%>
          </ul>
        </div>
    </div>
  </div>
</div>
<%# <%= link_to 'new',new_my_blog_path%> 

app/views/my_blogs/new.html.erb
<h1 class="text-align-center">New My Blog</h1>

<%= render 'form', my_blog: @my_blog  %>

<%= link_to 'Back', my_blogs_path %>

app/views/my_blogs/show.html.erb
<div class="show">
<%# <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">  
      <%= link_to 'Home',root_path %>
    <%# </li>
    <li class="breadcrumb-item " aria-current="page"><%= @my_blog.category.category %></li>
    <%# <li class="breadcrumb-item " aria-current="page"><%=  @my_blog.title %></li>
  <%# </ol> %>
<%# </nav>  %>

<p class="title-show">
  <%= @my_blog.title %>
</p>

<p class="img-show"><% if @my_blog.image.present? %>

  <%= image_tag @my_blog.image ,class:"img-class"%><% end %>

</p>
<%# <p class="cate-show">
  Category:-<%= @my_blog.category.category %>
<%# </p> %>
<p class="body-show">
  <%= @my_blog.body %>
</p>



<div class="links">
<%= link_to 'Edit', edit_my_blog_path(@my_blog),class:"btn btn-primary" %> |
<%= link_to 'Back', my_blogs_path,class:"btn btn-success  " %>
</div>
</div>